export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const CHANGE_TASK_REQUEST = 'CHANGE_TASK_REQUEST';
export const CHANGE_TASK_SUCCESS = 'CHANGE_TASK_SUCCESS';
export const CHANGE_TASK_FAIL = 'CHANGE_TASK_FAIL';
export const CHANGE_TASK_RESET = 'CHANGE_TASK_RESET';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
export const CREATE_TASK_RESET = 'CREATE_TASK_RESET';

export const EDIT_TASK = 'EDIT_TASK';
export const RESET_EDIT_TASK = 'RESET_EDIT_TASK';
